// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __imagerstreams_h__
#define __imagerstreams_h__

#include "imagerstreams_RcppExports.h"

#endif // __imagerstreams_h__
