# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
open_display <- function(width, height, title = "") {
    .Call('imagerstreams_open_display', PACKAGE = 'imagerstreams', width, height, title)
}

#' @export
close_display <- function(dsp) {
    invisible(.Call('imagerstreams_close_display', PACKAGE = 'imagerstreams', dsp))
}

#' @export
display_show <- function(dsp, im) {
    invisible(.Call('imagerstreams_display_show', PACKAGE = 'imagerstreams', dsp, im))
}

#' @export
getFrame <- function(file) {
    .Call('imagerstreams_getFrame', PACKAGE = 'imagerstreams', file)
}

#' @export
open_stream <- function(file) {
    .Call('imagerstreams_open_stream', PACKAGE = 'imagerstreams', file)
}

#' @export
open_camera <- function(device = 0L) {
    .Call('imagerstreams_open_camera', PACKAGE = 'imagerstreams', device)
}

#' @export
close_stream <- function(cap) {
    invisible(.Call('imagerstreams_close_stream', PACKAGE = 'imagerstreams', cap))
}

#' @export
stream_skipto <- function(cap, frame = 1L) {
    invisible(.Call('imagerstreams_stream_skipto', PACKAGE = 'imagerstreams', cap, frame))
}

#' @export
stream_info <- function(cap) {
    .Call('imagerstreams_stream_info', PACKAGE = 'imagerstreams', cap)
}

#' @export
stream_status <- function(cap) {
    .Call('imagerstreams_stream_status', PACKAGE = 'imagerstreams', cap)
}

#' @export
next_frame <- function(cap) {
    .Call('imagerstreams_next_frame', PACKAGE = 'imagerstreams', cap)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('imagerstreams_RcppExport_registerCCallable', PACKAGE = 'imagerstreams')
})
